// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/protos/hub.proto

package pb // import "pkg/protos/pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NoTransactionCallRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	TransactionID        string   `protobuf:"bytes,3,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	Payload              []byte   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Signer               []byte   `protobuf:"bytes,5,opt,name=signer,proto3" json:"signer,omitempty"`
	Timestamp            int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoTransactionCallRequest) Reset()         { *m = NoTransactionCallRequest{} }
func (m *NoTransactionCallRequest) String() string { return proto.CompactTextString(m) }
func (*NoTransactionCallRequest) ProtoMessage()    {}
func (*NoTransactionCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_26c1790866c244e7, []int{0}
}
func (m *NoTransactionCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoTransactionCallRequest.Unmarshal(m, b)
}
func (m *NoTransactionCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoTransactionCallRequest.Marshal(b, m, deterministic)
}
func (dst *NoTransactionCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoTransactionCallRequest.Merge(dst, src)
}
func (m *NoTransactionCallRequest) XXX_Size() int {
	return xxx_messageInfo_NoTransactionCallRequest.Size(m)
}
func (m *NoTransactionCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NoTransactionCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NoTransactionCallRequest proto.InternalMessageInfo

func (m *NoTransactionCallRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *NoTransactionCallRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *NoTransactionCallRequest) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *NoTransactionCallRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *NoTransactionCallRequest) GetSigner() []byte {
	if m != nil {
		return m.Signer
	}
	return nil
}

func (m *NoTransactionCallRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type FabricPayload struct {
	ChannelID            string   `protobuf:"bytes,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	ChainCodeName        string   `protobuf:"bytes,2,opt,name=chainCodeName,proto3" json:"chainCodeName,omitempty"`
	FncName              string   `protobuf:"bytes,3,opt,name=fncName,proto3" json:"fncName,omitempty"`
	Args                 []string `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FabricPayload) Reset()         { *m = FabricPayload{} }
func (m *FabricPayload) String() string { return proto.CompactTextString(m) }
func (*FabricPayload) ProtoMessage()    {}
func (*FabricPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_26c1790866c244e7, []int{1}
}
func (m *FabricPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FabricPayload.Unmarshal(m, b)
}
func (m *FabricPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FabricPayload.Marshal(b, m, deterministic)
}
func (dst *FabricPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FabricPayload.Merge(dst, src)
}
func (m *FabricPayload) XXX_Size() int {
	return xxx_messageInfo_FabricPayload.Size(m)
}
func (m *FabricPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_FabricPayload.DiscardUnknown(m)
}

var xxx_messageInfo_FabricPayload proto.InternalMessageInfo

func (m *FabricPayload) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *FabricPayload) GetChainCodeName() string {
	if m != nil {
		return m.ChainCodeName
	}
	return ""
}

func (m *FabricPayload) GetFncName() string {
	if m != nil {
		return m.FncName
	}
	return ""
}

func (m *FabricPayload) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type StartTransactionRequest struct {
	ChannelID            string   `protobuf:"bytes,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	TransactionID        string   `protobuf:"bytes,2,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	ChainCodes           []string `protobuf:"bytes,3,rep,name=chainCodes,proto3" json:"chainCodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartTransactionRequest) Reset()         { *m = StartTransactionRequest{} }
func (m *StartTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*StartTransactionRequest) ProtoMessage()    {}
func (*StartTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_26c1790866c244e7, []int{2}
}
func (m *StartTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartTransactionRequest.Unmarshal(m, b)
}
func (m *StartTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *StartTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartTransactionRequest.Merge(dst, src)
}
func (m *StartTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_StartTransactionRequest.Size(m)
}
func (m *StartTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartTransactionRequest proto.InternalMessageInfo

func (m *StartTransactionRequest) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *StartTransactionRequest) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *StartTransactionRequest) GetChainCodes() []string {
	if m != nil {
		return m.ChainCodes
	}
	return nil
}

type SendTransactionRequest struct {
	ChannelID            string   `protobuf:"bytes,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	TransactionID        string   `protobuf:"bytes,3,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	TransactionSeq       uint32   `protobuf:"varint,4,opt,name=transactionSeq,proto3" json:"transactionSeq,omitempty"`
	ChainCodeName        string   `protobuf:"bytes,5,opt,name=chainCodeName,proto3" json:"chainCodeName,omitempty"`
	FncName              string   `protobuf:"bytes,6,opt,name=fncName,proto3" json:"fncName,omitempty"`
	Args                 []string `protobuf:"bytes,7,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTransactionRequest) Reset()         { *m = SendTransactionRequest{} }
func (m *SendTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*SendTransactionRequest) ProtoMessage()    {}
func (*SendTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_26c1790866c244e7, []int{3}
}
func (m *SendTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionRequest.Unmarshal(m, b)
}
func (m *SendTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *SendTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionRequest.Merge(dst, src)
}
func (m *SendTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_SendTransactionRequest.Size(m)
}
func (m *SendTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionRequest proto.InternalMessageInfo

func (m *SendTransactionRequest) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *SendTransactionRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SendTransactionRequest) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *SendTransactionRequest) GetTransactionSeq() uint32 {
	if m != nil {
		return m.TransactionSeq
	}
	return 0
}

func (m *SendTransactionRequest) GetChainCodeName() string {
	if m != nil {
		return m.ChainCodeName
	}
	return ""
}

func (m *SendTransactionRequest) GetFncName() string {
	if m != nil {
		return m.FncName
	}
	return ""
}

func (m *SendTransactionRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type CommitTransactionRequest struct {
	ChannelID            string   `protobuf:"bytes,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	TransactionID        string   `protobuf:"bytes,2,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitTransactionRequest) Reset()         { *m = CommitTransactionRequest{} }
func (m *CommitTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*CommitTransactionRequest) ProtoMessage()    {}
func (*CommitTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_26c1790866c244e7, []int{4}
}
func (m *CommitTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitTransactionRequest.Unmarshal(m, b)
}
func (m *CommitTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *CommitTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitTransactionRequest.Merge(dst, src)
}
func (m *CommitTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_CommitTransactionRequest.Size(m)
}
func (m *CommitTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitTransactionRequest proto.InternalMessageInfo

func (m *CommitTransactionRequest) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *CommitTransactionRequest) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

type CommonResponseMessage struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	TransactionID        string   `protobuf:"bytes,3,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	Payload              []byte   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Signer               []byte   `protobuf:"bytes,5,opt,name=signer,proto3" json:"signer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResponseMessage) Reset()         { *m = CommonResponseMessage{} }
func (m *CommonResponseMessage) String() string { return proto.CompactTextString(m) }
func (*CommonResponseMessage) ProtoMessage()    {}
func (*CommonResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_26c1790866c244e7, []int{5}
}
func (m *CommonResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponseMessage.Unmarshal(m, b)
}
func (m *CommonResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponseMessage.Marshal(b, m, deterministic)
}
func (dst *CommonResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponseMessage.Merge(dst, src)
}
func (m *CommonResponseMessage) XXX_Size() int {
	return xxx_messageInfo_CommonResponseMessage.Size(m)
}
func (m *CommonResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponseMessage proto.InternalMessageInfo

func (m *CommonResponseMessage) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *CommonResponseMessage) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *CommonResponseMessage) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *CommonResponseMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *CommonResponseMessage) GetSigner() []byte {
	if m != nil {
		return m.Signer
	}
	return nil
}

func init() {
	proto.RegisterType((*NoTransactionCallRequest)(nil), "NoTransactionCallRequest")
	proto.RegisterType((*FabricPayload)(nil), "FabricPayload")
	proto.RegisterType((*StartTransactionRequest)(nil), "StartTransactionRequest")
	proto.RegisterType((*SendTransactionRequest)(nil), "SendTransactionRequest")
	proto.RegisterType((*CommitTransactionRequest)(nil), "CommitTransactionRequest")
	proto.RegisterType((*CommonResponseMessage)(nil), "CommonResponseMessage")
}

func init() { proto.RegisterFile("pkg/protos/hub.proto", fileDescriptor_hub_26c1790866c244e7) }

var fileDescriptor_hub_26c1790866c244e7 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x94, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xc7, 0x71, 0x92, 0xcd, 0xaa, 0x23, 0xb2, 0xcb, 0x5a, 0xd0, 0xf5, 0xa2, 0x15, 0x8a, 0x22,
	0x84, 0x7a, 0xca, 0x4a, 0xf0, 0x06, 0xb4, 0x5a, 0xb5, 0x07, 0x2a, 0x94, 0x72, 0xe2, 0x80, 0xe4,
	0x24, 0x6e, 0x1a, 0x91, 0xd8, 0x69, 0xec, 0x1c, 0x38, 0x70, 0xe0, 0x19, 0x78, 0x08, 0x5e, 0x80,
	0xc7, 0xe2, 0x21, 0x50, 0x4c, 0x4a, 0xd3, 0x36, 0x69, 0xe1, 0x80, 0xb8, 0x8d, 0xff, 0xa3, 0xcc,
	0xc7, 0x6f, 0x66, 0x02, 0x8f, 0x8b, 0x8f, 0xc9, 0x5d, 0x51, 0x0a, 0x25, 0xe4, 0xdd, 0xaa, 0x0a,
	0x7d, 0x6d, 0x7a, 0xdf, 0x11, 0x90, 0xb9, 0x78, 0x57, 0x52, 0x2e, 0x69, 0xa4, 0x52, 0xc1, 0xc7,
	0x34, 0xcb, 0x02, 0xb6, 0xae, 0x98, 0x54, 0x18, 0x83, 0xb5, 0x2c, 0x45, 0x4e, 0x90, 0x8b, 0x46,
	0x83, 0x40, 0xdb, 0xf8, 0x02, 0x0c, 0x25, 0x88, 0xa1, 0x15, 0x43, 0x09, 0xfc, 0x1c, 0x1c, 0xb5,
	0xfd, 0x7a, 0x36, 0x21, 0xa6, 0x76, 0xed, 0x8a, 0x98, 0xc0, 0x79, 0x41, 0x3f, 0x65, 0x82, 0xc6,
	0xc4, 0x72, 0xd1, 0xe8, 0x61, 0xb0, 0x79, 0xe2, 0x21, 0xd8, 0x32, 0x4d, 0x38, 0x2b, 0xc9, 0x99,
	0x76, 0x34, 0x2f, 0x7c, 0x0b, 0x03, 0x95, 0xe6, 0x4c, 0x2a, 0x9a, 0x17, 0xc4, 0x76, 0xd1, 0xc8,
	0x0c, 0xb6, 0x82, 0xf7, 0x05, 0x81, 0x73, 0x4f, 0xc3, 0x32, 0x8d, 0xde, 0x36, 0x71, 0x6e, 0x61,
	0x10, 0xad, 0x28, 0xe7, 0x2c, 0x9b, 0x4d, 0x9a, 0x82, 0xb7, 0x42, 0x5d, 0x65, 0xb4, 0xa2, 0x29,
	0x1f, 0x8b, 0x98, 0xcd, 0x69, 0xce, 0x9a, 0x06, 0x76, 0xc5, 0xba, 0xca, 0x25, 0x8f, 0xb4, 0xff,
	0x57, 0x17, 0x9b, 0x67, 0x4d, 0x82, 0x96, 0x89, 0x24, 0x96, 0x6b, 0xd6, 0x24, 0x6a, 0xdb, 0xfb,
	0x0c, 0xd7, 0x0b, 0x45, 0x4b, 0xd5, 0x82, 0xb7, 0x01, 0x77, 0xb2, 0x98, 0x5d, 0x64, 0x46, 0x17,
	0xb2, 0x67, 0x00, 0xbf, 0xab, 0x93, 0xc4, 0xd4, 0x89, 0x5b, 0x8a, 0xf7, 0x03, 0xc1, 0x70, 0xc1,
	0x78, 0xfc, 0xd7, 0xe9, 0x31, 0x58, 0x55, 0x95, 0xc6, 0x4d, 0x56, 0x6d, 0xff, 0xe1, 0x14, 0x5f,
	0xc0, 0x45, 0x4b, 0x58, 0xb0, 0xb5, 0x1e, 0xa6, 0x13, 0xec, 0xa9, 0x87, 0xb4, 0xcf, 0x4e, 0xd0,
	0xb6, 0xbb, 0x69, 0x9f, 0xb7, 0x68, 0x7f, 0x00, 0x32, 0x16, 0x79, 0x9e, 0xfe, 0x23, 0xdc, 0xde,
	0x57, 0x04, 0x4f, 0xea, 0x04, 0x75, 0x54, 0x59, 0x08, 0x2e, 0xd9, 0x1b, 0x26, 0x25, 0x4d, 0xd8,
	0xff, 0xbc, 0x82, 0x97, 0xdf, 0x0c, 0x30, 0xa7, 0x55, 0x88, 0xa7, 0x70, 0x75, 0x70, 0xa5, 0xf8,
	0xc6, 0xef, 0xbb, 0xdc, 0xa7, 0x43, 0xbf, 0xb3, 0x17, 0xef, 0x01, 0xbe, 0x87, 0x47, 0xfb, 0x5b,
	0x8b, 0x89, 0xdf, 0xb3, 0xc8, 0x47, 0xe2, 0x4c, 0xe0, 0x72, 0x6f, 0xfb, 0xf0, 0xb5, 0xdf, 0xbd,
	0x8f, 0x47, 0xa2, 0x4c, 0xe1, 0xea, 0x60, 0xaa, 0xf8, 0xc6, 0xef, 0x9b, 0x74, 0x7f, 0xa4, 0xd7,
	0x97, 0xef, 0x9d, 0xd6, 0x0f, 0xae, 0x08, 0x43, 0x5b, 0x9b, 0xaf, 0x7e, 0x06, 0x00, 0x00, 0xff,
	0xff, 0xb7, 0xf6, 0x3b, 0x70, 0xf8, 0x04, 0x00, 0x00,
}
