// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/protos/hub.proto

package pb // import "pkg/protos/pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NoTransactionCallRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	TransactionID        string   `protobuf:"bytes,3,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	StepID               string   `protobuf:"bytes,4,opt,name=stepID,proto3" json:"stepID,omitempty"`
	Payload              []byte   `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Signer               []byte   `protobuf:"bytes,6,opt,name=signer,proto3" json:"signer,omitempty"`
	Timestamp            int64    `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoTransactionCallRequest) Reset()         { *m = NoTransactionCallRequest{} }
func (m *NoTransactionCallRequest) String() string { return proto.CompactTextString(m) }
func (*NoTransactionCallRequest) ProtoMessage()    {}
func (*NoTransactionCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_7f50494d4c4514e7, []int{0}
}
func (m *NoTransactionCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoTransactionCallRequest.Unmarshal(m, b)
}
func (m *NoTransactionCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoTransactionCallRequest.Marshal(b, m, deterministic)
}
func (dst *NoTransactionCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoTransactionCallRequest.Merge(dst, src)
}
func (m *NoTransactionCallRequest) XXX_Size() int {
	return xxx_messageInfo_NoTransactionCallRequest.Size(m)
}
func (m *NoTransactionCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NoTransactionCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NoTransactionCallRequest proto.InternalMessageInfo

func (m *NoTransactionCallRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *NoTransactionCallRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *NoTransactionCallRequest) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *NoTransactionCallRequest) GetStepID() string {
	if m != nil {
		return m.StepID
	}
	return ""
}

func (m *NoTransactionCallRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *NoTransactionCallRequest) GetSigner() []byte {
	if m != nil {
		return m.Signer
	}
	return nil
}

func (m *NoTransactionCallRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type FabricPayloadRequest struct {
	ChannelName          string          `protobuf:"bytes,1,opt,name=channelName,proto3" json:"channelName,omitempty"`
	ChainCodeName        string          `protobuf:"bytes,2,opt,name=chainCodeName,proto3" json:"chainCodeName,omitempty"`
	FncName              string          `protobuf:"bytes,3,opt,name=fncName,proto3" json:"fncName,omitempty"`
	Args                 []string        `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Callback             *FabricCallback `protobuf:"bytes,5,opt,name=callback,proto3" json:"callback,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FabricPayloadRequest) Reset()         { *m = FabricPayloadRequest{} }
func (m *FabricPayloadRequest) String() string { return proto.CompactTextString(m) }
func (*FabricPayloadRequest) ProtoMessage()    {}
func (*FabricPayloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_7f50494d4c4514e7, []int{1}
}
func (m *FabricPayloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FabricPayloadRequest.Unmarshal(m, b)
}
func (m *FabricPayloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FabricPayloadRequest.Marshal(b, m, deterministic)
}
func (dst *FabricPayloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FabricPayloadRequest.Merge(dst, src)
}
func (m *FabricPayloadRequest) XXX_Size() int {
	return xxx_messageInfo_FabricPayloadRequest.Size(m)
}
func (m *FabricPayloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FabricPayloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FabricPayloadRequest proto.InternalMessageInfo

func (m *FabricPayloadRequest) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *FabricPayloadRequest) GetChainCodeName() string {
	if m != nil {
		return m.ChainCodeName
	}
	return ""
}

func (m *FabricPayloadRequest) GetFncName() string {
	if m != nil {
		return m.FncName
	}
	return ""
}

func (m *FabricPayloadRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *FabricPayloadRequest) GetCallback() *FabricCallback {
	if m != nil {
		return m.Callback
	}
	return nil
}

type FabricCallback struct {
	CallbackChannelName   string   `protobuf:"bytes,1,opt,name=callbackChannelName,proto3" json:"callbackChannelName,omitempty"`
	CallbackChainCodeName string   `protobuf:"bytes,2,opt,name=callbackChainCodeName,proto3" json:"callbackChainCodeName,omitempty"`
	CallbackFncName       string   `protobuf:"bytes,3,opt,name=callbackFncName,proto3" json:"callbackFncName,omitempty"`
	CallbackArgs          []string `protobuf:"bytes,4,rep,name=callbackArgs,proto3" json:"callbackArgs,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *FabricCallback) Reset()         { *m = FabricCallback{} }
func (m *FabricCallback) String() string { return proto.CompactTextString(m) }
func (*FabricCallback) ProtoMessage()    {}
func (*FabricCallback) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_7f50494d4c4514e7, []int{2}
}
func (m *FabricCallback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FabricCallback.Unmarshal(m, b)
}
func (m *FabricCallback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FabricCallback.Marshal(b, m, deterministic)
}
func (dst *FabricCallback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FabricCallback.Merge(dst, src)
}
func (m *FabricCallback) XXX_Size() int {
	return xxx_messageInfo_FabricCallback.Size(m)
}
func (m *FabricCallback) XXX_DiscardUnknown() {
	xxx_messageInfo_FabricCallback.DiscardUnknown(m)
}

var xxx_messageInfo_FabricCallback proto.InternalMessageInfo

func (m *FabricCallback) GetCallbackChannelName() string {
	if m != nil {
		return m.CallbackChannelName
	}
	return ""
}

func (m *FabricCallback) GetCallbackChainCodeName() string {
	if m != nil {
		return m.CallbackChainCodeName
	}
	return ""
}

func (m *FabricCallback) GetCallbackFncName() string {
	if m != nil {
		return m.CallbackFncName
	}
	return ""
}

func (m *FabricCallback) GetCallbackArgs() []string {
	if m != nil {
		return m.CallbackArgs
	}
	return nil
}

type StartTransactionRequest struct {
	ChannelID            string   `protobuf:"bytes,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	TransactionID        string   `protobuf:"bytes,2,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	ChainCodes           []string `protobuf:"bytes,3,rep,name=chainCodes,proto3" json:"chainCodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartTransactionRequest) Reset()         { *m = StartTransactionRequest{} }
func (m *StartTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*StartTransactionRequest) ProtoMessage()    {}
func (*StartTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_7f50494d4c4514e7, []int{3}
}
func (m *StartTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartTransactionRequest.Unmarshal(m, b)
}
func (m *StartTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *StartTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartTransactionRequest.Merge(dst, src)
}
func (m *StartTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_StartTransactionRequest.Size(m)
}
func (m *StartTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartTransactionRequest proto.InternalMessageInfo

func (m *StartTransactionRequest) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *StartTransactionRequest) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *StartTransactionRequest) GetChainCodes() []string {
	if m != nil {
		return m.ChainCodes
	}
	return nil
}

type SendTransactionRequest struct {
	ChannelID            string   `protobuf:"bytes,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	TransactionID        string   `protobuf:"bytes,3,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	TransactionSeq       uint32   `protobuf:"varint,4,opt,name=transactionSeq,proto3" json:"transactionSeq,omitempty"`
	ChainCodeName        string   `protobuf:"bytes,5,opt,name=chainCodeName,proto3" json:"chainCodeName,omitempty"`
	FncName              string   `protobuf:"bytes,6,opt,name=fncName,proto3" json:"fncName,omitempty"`
	Args                 []string `protobuf:"bytes,7,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTransactionRequest) Reset()         { *m = SendTransactionRequest{} }
func (m *SendTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*SendTransactionRequest) ProtoMessage()    {}
func (*SendTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_7f50494d4c4514e7, []int{4}
}
func (m *SendTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionRequest.Unmarshal(m, b)
}
func (m *SendTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *SendTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionRequest.Merge(dst, src)
}
func (m *SendTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_SendTransactionRequest.Size(m)
}
func (m *SendTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionRequest proto.InternalMessageInfo

func (m *SendTransactionRequest) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *SendTransactionRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SendTransactionRequest) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *SendTransactionRequest) GetTransactionSeq() uint32 {
	if m != nil {
		return m.TransactionSeq
	}
	return 0
}

func (m *SendTransactionRequest) GetChainCodeName() string {
	if m != nil {
		return m.ChainCodeName
	}
	return ""
}

func (m *SendTransactionRequest) GetFncName() string {
	if m != nil {
		return m.FncName
	}
	return ""
}

func (m *SendTransactionRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type CommitTransactionRequest struct {
	ChannelID            string   `protobuf:"bytes,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	TransactionID        string   `protobuf:"bytes,2,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitTransactionRequest) Reset()         { *m = CommitTransactionRequest{} }
func (m *CommitTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*CommitTransactionRequest) ProtoMessage()    {}
func (*CommitTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_7f50494d4c4514e7, []int{5}
}
func (m *CommitTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitTransactionRequest.Unmarshal(m, b)
}
func (m *CommitTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitTransactionRequest.Marshal(b, m, deterministic)
}
func (dst *CommitTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitTransactionRequest.Merge(dst, src)
}
func (m *CommitTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_CommitTransactionRequest.Size(m)
}
func (m *CommitTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitTransactionRequest proto.InternalMessageInfo

func (m *CommitTransactionRequest) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *CommitTransactionRequest) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

type CommonResponseMessage struct {
	From          string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	TransactionID string `protobuf:"bytes,3,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	// 用于区别一个事务多个操作
	StepID               string   `protobuf:"bytes,4,opt,name=stepID,proto3" json:"stepID,omitempty"`
	Payload              []byte   `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Signer               []byte   `protobuf:"bytes,6,opt,name=signer,proto3" json:"signer,omitempty"`
	Callback             []byte   `protobuf:"bytes,7,opt,name=callback,proto3" json:"callback,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResponseMessage) Reset()         { *m = CommonResponseMessage{} }
func (m *CommonResponseMessage) String() string { return proto.CompactTextString(m) }
func (*CommonResponseMessage) ProtoMessage()    {}
func (*CommonResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_7f50494d4c4514e7, []int{6}
}
func (m *CommonResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponseMessage.Unmarshal(m, b)
}
func (m *CommonResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponseMessage.Marshal(b, m, deterministic)
}
func (dst *CommonResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponseMessage.Merge(dst, src)
}
func (m *CommonResponseMessage) XXX_Size() int {
	return xxx_messageInfo_CommonResponseMessage.Size(m)
}
func (m *CommonResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponseMessage proto.InternalMessageInfo

func (m *CommonResponseMessage) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *CommonResponseMessage) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *CommonResponseMessage) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *CommonResponseMessage) GetStepID() string {
	if m != nil {
		return m.StepID
	}
	return ""
}

func (m *CommonResponseMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *CommonResponseMessage) GetSigner() []byte {
	if m != nil {
		return m.Signer
	}
	return nil
}

func (m *CommonResponseMessage) GetCallback() []byte {
	if m != nil {
		return m.Callback
	}
	return nil
}

func init() {
	proto.RegisterType((*NoTransactionCallRequest)(nil), "NoTransactionCallRequest")
	proto.RegisterType((*FabricPayloadRequest)(nil), "FabricPayloadRequest")
	proto.RegisterType((*FabricCallback)(nil), "FabricCallback")
	proto.RegisterType((*StartTransactionRequest)(nil), "StartTransactionRequest")
	proto.RegisterType((*SendTransactionRequest)(nil), "SendTransactionRequest")
	proto.RegisterType((*CommitTransactionRequest)(nil), "CommitTransactionRequest")
	proto.RegisterType((*CommonResponseMessage)(nil), "CommonResponseMessage")
}

func init() { proto.RegisterFile("pkg/protos/hub.proto", fileDescriptor_hub_7f50494d4c4514e7) }

var fileDescriptor_hub_7f50494d4c4514e7 = []byte{
	// 539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0x41, 0x6e, 0xd3, 0x40,
	0x14, 0xc5, 0x76, 0x9a, 0x90, 0xdf, 0x26, 0xa1, 0x43, 0x9b, 0x4e, 0xab, 0x0a, 0x59, 0x16, 0x42,
	0x91, 0x90, 0x5c, 0x54, 0xb8, 0x00, 0x38, 0x8a, 0x92, 0x05, 0x15, 0x72, 0x58, 0xb1, 0x40, 0x1a,
	0x3b, 0xd3, 0xc4, 0xaa, 0xed, 0x71, 0x3d, 0xe3, 0x05, 0x0b, 0xce, 0xc3, 0x19, 0xb8, 0x00, 0x6c,
	0x38, 0x0a, 0x87, 0x40, 0x9e, 0xd8, 0xb1, 0x1d, 0x3b, 0x01, 0x16, 0x48, 0xec, 0xfe, 0x7f, 0x6f,
	0xe6, 0xcf, 0x7f, 0x7f, 0x9e, 0xc7, 0x70, 0x12, 0xdd, 0x2d, 0xaf, 0xa2, 0x98, 0x09, 0xc6, 0xaf,
	0x56, 0x89, 0x63, 0xca, 0xd0, 0xf8, 0xa1, 0x00, 0xbe, 0x61, 0xef, 0x63, 0x12, 0x72, 0xe2, 0x0a,
	0x8f, 0x85, 0x16, 0xf1, 0x7d, 0x9b, 0xde, 0x27, 0x94, 0x0b, 0x84, 0xa0, 0x75, 0x1b, 0xb3, 0x00,
	0x2b, 0xba, 0x32, 0xea, 0xda, 0x32, 0x46, 0x7d, 0x50, 0x05, 0xc3, 0xaa, 0x44, 0x54, 0xc1, 0xd0,
	0x53, 0xe8, 0x89, 0x62, 0xf7, 0x6c, 0x8c, 0x35, 0x49, 0x55, 0x41, 0x34, 0x84, 0x36, 0x17, 0x34,
	0x9a, 0x8d, 0x71, 0x4b, 0xd2, 0x59, 0x86, 0x30, 0x74, 0x22, 0xf2, 0xc9, 0x67, 0x64, 0x81, 0x0f,
	0x74, 0x65, 0x74, 0x64, 0xe7, 0xa9, 0xdc, 0xe1, 0x2d, 0x43, 0x1a, 0xe3, 0xb6, 0x24, 0xb2, 0x0c,
	0x5d, 0x42, 0x57, 0x78, 0x01, 0xe5, 0x82, 0x04, 0x11, 0xee, 0xe8, 0xca, 0x48, 0xb3, 0x0b, 0xc0,
	0xf8, 0xaa, 0xc0, 0xc9, 0x84, 0x38, 0xb1, 0xe7, 0xbe, 0x5b, 0xd7, 0xc9, 0xa5, 0xe8, 0x70, 0xe8,
	0xae, 0x48, 0x18, 0x52, 0xff, 0x86, 0x04, 0x34, 0x53, 0x54, 0x86, 0x52, 0x21, 0xee, 0x8a, 0x78,
	0xa1, 0xc5, 0x16, 0x54, 0xae, 0x59, 0x6b, 0xac, 0x82, 0x69, 0xc3, 0xb7, 0xa1, 0x2b, 0xf9, 0xb5,
	0xd0, 0x3c, 0x4d, 0x87, 0x45, 0xe2, 0x25, 0xc7, 0x2d, 0x5d, 0x4b, 0x87, 0x95, 0xc6, 0xe8, 0x39,
	0x3c, 0x74, 0x89, 0xef, 0x3b, 0xc4, 0xbd, 0x93, 0xfa, 0x0e, 0xaf, 0x07, 0xe6, 0xba, 0x3d, 0x2b,
	0x83, 0xed, 0xcd, 0x02, 0xe3, 0x9b, 0x02, 0xfd, 0x2a, 0x89, 0x5e, 0xc0, 0xe3, 0x9c, 0xb6, 0x6a,
	0xdd, 0x37, 0x51, 0xe8, 0x15, 0x9c, 0x96, 0xe0, 0x9a, 0x9a, 0x66, 0x12, 0x8d, 0x60, 0x90, 0x13,
	0x93, 0x8a, 0xba, 0x6d, 0x18, 0x19, 0x70, 0x94, 0x43, 0xaf, 0x0b, 0xb5, 0x15, 0xcc, 0xf8, 0x0c,
	0x67, 0x73, 0x41, 0x62, 0x51, 0x72, 0x55, 0x7e, 0x0d, 0x97, 0xd0, 0xcd, 0x66, 0x3e, 0x1b, 0x67,
	0x32, 0x0a, 0xa0, 0xee, 0x25, 0xb5, 0xc9, 0x4b, 0x4f, 0x00, 0x36, 0x77, 0xc2, 0xb1, 0x26, 0x1b,
	0x28, 0x21, 0xc6, 0x4f, 0x05, 0x86, 0x73, 0x1a, 0x2e, 0xfe, 0xfa, 0x78, 0x04, 0xad, 0x24, 0xf1,
	0x16, 0xd9, 0xa9, 0x32, 0xfe, 0x43, 0x7b, 0x3f, 0x83, 0x7e, 0x09, 0x98, 0xd3, 0x7b, 0x69, 0xf3,
	0x9e, 0xbd, 0x85, 0xd6, 0x3d, 0x76, 0xf0, 0x1b, 0x8f, 0xb5, 0x9b, 0x3d, 0xd6, 0x29, 0x3c, 0x66,
	0x7c, 0x04, 0x6c, 0xb1, 0x20, 0xf0, 0xfe, 0xd1, 0xb8, 0x8d, 0xef, 0x0a, 0x9c, 0xa6, 0x07, 0xa4,
	0x55, 0x79, 0xc4, 0x42, 0x4e, 0xdf, 0x52, 0xce, 0xc9, 0x92, 0xfe, 0x97, 0xcf, 0xc3, 0x45, 0xe9,
	0x8b, 0xeb, 0x48, 0x66, 0x93, 0x5f, 0x7f, 0x51, 0x41, 0x9b, 0x26, 0x0e, 0x9a, 0xc2, 0x71, 0xed,
	0xc9, 0x43, 0xe7, 0xe6, 0xae, 0x67, 0xf0, 0x62, 0x68, 0x36, 0xea, 0x37, 0x1e, 0xa0, 0x09, 0x3c,
	0xda, 0x76, 0x3a, 0xc2, 0xe6, 0x0e, 0xf3, 0xef, 0xa9, 0x33, 0x86, 0xc1, 0x96, 0x63, 0xd1, 0x99,
	0xd9, 0xec, 0xe1, 0x3d, 0x55, 0xa6, 0x70, 0x5c, 0x73, 0x02, 0x3a, 0x37, 0x77, 0xb9, 0x63, 0x77,
	0xa5, 0x37, 0x83, 0x0f, 0xbd, 0xd2, 0xdf, 0x22, 0x72, 0x9c, 0xb6, 0x0c, 0x5f, 0xfe, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0x8a, 0x20, 0x09, 0xec, 0x45, 0x06, 0x00, 0x00,
}
